### ISSUE TITLE
preset issue related to `preact/compat` 

### ISSUE THREAD

**Issue by armujahid** [preactjs/codesandbox-template#1]
Current codesandbox template transpiler is currently using `preact-compat` instead of `preact/compat` although it should load `preact/compat` if it's available. Otherwise it should fallback to `preact-compat` for Preact 8 sandboxes. Full issue can be seen here https://github.com/codesandbox/codesandbox-client/issues/3685

I am try to fix this so I thought I should link that issue here.

**Comment by marvinhagemeister** [comment]
The current Preact preset that's found on codesandbox is outside of our control. It lives in some internal Database of the codesandbox team. That's in fact the reason why we created this repo here :+1: We got in touch with the codesandbox team and they're happy to use one of our repos as a template once it's ready. It's very early and we just created it a day ago, so stay tuned!
